export const countriesCodes = {
    'Azerbaijan': 'AZ',
    'Albania': 'AL',
    'Armenia': 'AM',
    'Bosnia and Herzegovina': 'BA',
    'Bulgaria': 'BG',
    'Cyprus': 'CY',
    'Denmark': 'DK',
    'Ireland': 'IE',
    'Estonia': 'EE',
    'Austria': 'AT',
    'Finland': 'FI',
    'Czech Republic': 'CZ',
    'France': 'FR',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Greece': 'GR',
    'Croatia': 'HR',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'Israel': 'IL',
    'Italy': 'IT',
    'Latvia': 'LV',
    'Belarus': 'BY',
    'Slovakia': 'SK',
    'Liechtenstein': 'LI',
    'Lithuania': 'LT',
    'The former Yugoslav Republic of Macedonia': 'MK',
    'Malta': 'MT',
    'Belgium': 'BE',
    'Faroe Islands': 'FO',
    'Andorra': 'AD',
    'Luxembourg': 'LU',
    'Monaco': 'MC',
    'Montenegro': 'ME',
    'Netherlands': 'NL',
    'Norway': 'NO',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Romania': 'RO',
    'Republic of Moldova': 'MD',
    'Slovenia': 'SI',
    'Spain': 'ES',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Turkey': 'TR',
    'United Kingdom': 'GB',
    'Ukraine': 'UA',
    'San Marino': 'SM',
    'Serbia': 'RS',
    'Holy See (Vatican City)': 'VA',
    'Russia': 'RU',
  };
